### ISSUE TITLE
problem with LaTeX2e <2023-06-01>

### ISSUE THREAD

**Issue by ratosse** [ho-tex/catchfile#1]
Hello,
I'm using TeXlive 2023 and since updating latex from LaTeX2e <2022-11-01> patch level 1 (version 65161) to LaTeX2e <2023-06-01> (version 67314), I can't use macro getenv defined in the example.
[catch.zip](https://github.com/ho-tex/catchfile/files/11769372/catch.zip)
zip file contains tex file and log files with two versions logok (65161) and logko (67314).
I don't have found how to resolve this problem, so I submit it.
Thank you

**Comment by u-fischer** [comment]
That is a LaTeX problem and I opened an issue there: https://github.com/latex3/latex2e/issues/1092

**Comment by u-fischer** [comment]
We will push a fix soon, until then you should be able to work around by putting this in your preamble:

~~~~
\ExplSyntaxOn\makeatletter
\cs_set:Npn \IfFileExists@@ #1
  {
    \tl_if_blank:nF {#1}
      {
        \tl_if_head_eq_charcode:oNTF { \use:n #1 } |
          {#1}
          { \file_full_name:n {#1} }
      }
  }
\cs_generate_variant:Nn \tl_if_head_eq_charcode:nNTF { o }
\ExplSyntaxOff\makeatother
~~~~

**Comment by u-fischer** [comment]
A new latex has been sent to ctan which resolves the issue, so closing here.
